Removed scipy dependency
posterior/goftests pull request #10
Opened 2016-08-31 14:55 UTC by tmarkovich

I have removed the scipy dependencies by using the gamma function that the python math module provides, and implementing my own $\chi^2$ survival function. This was done so that I could use goftests with pypy.

I have also included a test for my new $\chi^2$ survival function, and verified that it agrees with the scipy provided version to machine precision.

2016-08-31 21:29 UTC, jfinkels commented on goftests/utils.py
> +    F(x; s) = \frac{ \gamma( x/2, s/2 ) }{ \Gamma(s/2) },
This should be
```python
.. math::

   F(x; s) = ...
```

or for inline ``` :math:`F(x; s) = ...` ```.

2016-08-31 21:45 UTC, jfinkels commented on goftests/utils.py
> +    top = incomplete_gamma(x/2.0, s/2.0)
The `2.0`s and `1.0`s are all unnecessary as long as you have `from __future__ import division`; it's more readable to just do `x / 2`, etc.

2016-08-31 21:46 UTC, jfinkels commented on goftests/utils.py
> +    value = 0.0
This doesn't need to be defined at the top of the function :). Best to leave it close to where it is actually used.

2016-08-31 21:46 UTC, jfinkels commented on goftests/utils.py
> +    for k in range(0, 100):
The default first argument for range is zero, so this should just be `for k in range(100):`.

2016-08-31 21:47 UTC, jfinkels commented on goftests/utils.py
> +        log_num = (k + s)*log_x + (-x) + log_gamma_s
If the only use for `k` is in the expression `k + s`, you might want to just do `for k in range(s, s + 100):`

2016-08-31 21:50 UTC, jfinkels commented on goftests/utils.py
> +        log_denom = log(math.gamma(k + s + 1))
Can you use [`math.lgamma`][1] here? You may have mentioned this,  but I don't remember what the explanation was. It exists in both Python 2.7 and 3.2+.

[1]: https://docs.python.org/3/library/math.html#math.lgamma

2016-08-31 23:32 UTC, fritzo commented
@jfinkels I believe you are now be able to merge PRs on goftests. Feel free to merge this and future PRs. I can generally only maintain on weekends. Ping me if you need to update pypi, or I can share ownership.

@tmarkovich Thanks for making this change, it's great to remove a dependency!

2016-09-01 00:39 UTC, jfinkels commented
@fritzo Thanks! I merged the other pull request I made, and I'll merge this one after reviewing with @tmarkovich.

2016-09-01 02:21 UTC, tmarkovich commented
@jfinkels Thank you for pointing out how to use math mode in doc-strings. I hope that I implemented it properly. I also took your suggestion to use lgamma. It changed no test passage but appears to be cleaner and marginally faster.

I also removed this because It makes a better message here for developers than a comment for end users:
This was implemented so that we could use the goftests module
with pypy. Given that the only scipy dependence inside goftests
was from the chi^2 survival function (1 - cdf), and then gamma
function.

@fritzo I'm glad you like it!

2016-09-14 19:19 UTC, jfinkels requested changes
Hey Thomas, can you rebase this?

2017-03-31 03:41 UTC, jfinkels commented
This was superceded by pull request #15.

2017-03-31 03:41 UTC, closed without merging